var annotated_dup =
[
    [ "\u202APGE", null, [
      [ "\u202AColor", "class_p_g_e_1_1_color.html", "class_p_g_e_1_1_color" ],
      [ "\u202AException", "class_p_g_e_1_1_exception.html", "class_p_g_e_1_1_exception" ],
      [ "\u202AAbstractIO", "class_p_g_e_1_1_abstract_i_o.html", "class_p_g_e_1_1_abstract_i_o" ],
      [ "\u202ABinaryReader", "class_p_g_e_1_1_binary_reader.html", "class_p_g_e_1_1_binary_reader" ],
      [ "\u202ABinaryWriter", "class_p_g_e_1_1_binary_writer.html", "class_p_g_e_1_1_binary_writer" ],
      [ "\u202AFilePath", "class_p_g_e_1_1_file_path.html", "class_p_g_e_1_1_file_path" ],
      [ "\u202ATextReader", "class_p_g_e_1_1_text_reader.html", "class_p_g_e_1_1_text_reader" ],
      [ "\u202ATextWriter", "class_p_g_e_1_1_text_writer.html", "class_p_g_e_1_1_text_writer" ],
      [ "\u202AGraphics", "class_p_g_e_1_1_graphics.html", "class_p_g_e_1_1_graphics" ],
      [ "\u202AMaterial", "class_p_g_e_1_1_material.html", "class_p_g_e_1_1_material" ],
      [ "\u202AMesh", "class_p_g_e_1_1_mesh.html", "class_p_g_e_1_1_mesh" ],
      [ "\u202AShader", "class_p_g_e_1_1_shader.html", "class_p_g_e_1_1_shader" ],
      [ "\u202ATexture", "class_p_g_e_1_1_texture.html", "class_p_g_e_1_1_texture" ],
      [ "\u202AInput", "class_p_g_e_1_1_input.html", "class_p_g_e_1_1_input" ],
      [ "\u202AKeyboardInput", "class_p_g_e_1_1_keyboard_input.html", "class_p_g_e_1_1_keyboard_input" ],
      [ "\u202AMouseInput", "class_p_g_e_1_1_mouse_input.html", "class_p_g_e_1_1_mouse_input" ],
      [ "\u202AController", "class_p_g_e_1_1_controller.html", "class_p_g_e_1_1_controller" ],
      [ "\u202AControllerInput", "class_p_g_e_1_1_controller_input.html", "class_p_g_e_1_1_controller_input" ],
      [ "\u202AInputManager", "class_p_g_e_1_1_input_manager.html", "class_p_g_e_1_1_input_manager" ],
      [ "\u202AAABBox", "class_p_g_e_1_1_a_a_b_box.html", "class_p_g_e_1_1_a_a_b_box" ],
      [ "\u202AHasher", "class_p_g_e_1_1_hasher.html", "class_p_g_e_1_1_hasher" ],
      [ "\u202ALine2f", "class_p_g_e_1_1_line2f.html", "class_p_g_e_1_1_line2f" ],
      [ "\u202ALine3f", "class_p_g_e_1_1_line3f.html", "class_p_g_e_1_1_line3f" ],
      [ "\u202ALine2i", "class_p_g_e_1_1_line2i.html", "class_p_g_e_1_1_line2i" ],
      [ "\u202AMatrix4x4f", "class_p_g_e_1_1_matrix4x4f.html", "class_p_g_e_1_1_matrix4x4f" ],
      [ "\u202APlane", "class_p_g_e_1_1_plane.html", "class_p_g_e_1_1_plane" ],
      [ "\u202ARandom", "class_p_g_e_1_1_random.html", "class_p_g_e_1_1_random" ],
      [ "\u202ARectanglef", "class_p_g_e_1_1_rectanglef.html", "class_p_g_e_1_1_rectanglef" ],
      [ "\u202ARectanglei", "class_p_g_e_1_1_rectanglei.html", "class_p_g_e_1_1_rectanglei" ],
      [ "\u202AVector2f", "class_p_g_e_1_1_vector2f.html", "class_p_g_e_1_1_vector2f" ],
      [ "\u202AVector3f", "class_p_g_e_1_1_vector3f.html", "class_p_g_e_1_1_vector3f" ],
      [ "\u202AVector4f", "class_p_g_e_1_1_vector4f.html", "class_p_g_e_1_1_vector4f" ],
      [ "\u202AVector2i", "class_p_g_e_1_1_vector2i.html", "class_p_g_e_1_1_vector2i" ],
      [ "\u202ARawWrapper", "class_p_g_e_1_1_raw_wrapper.html", "class_p_g_e_1_1_raw_wrapper" ],
      [ "\u202AResourceBase", "class_p_g_e_1_1_resource_base.html", null ],
      [ "\u202AResource", "class_p_g_e_1_1_resource.html", "class_p_g_e_1_1_resource" ],
      [ "\u202AResourceManager", "class_p_g_e_1_1_resource_manager.html", "class_p_g_e_1_1_resource_manager" ],
      [ "\u202AResourceView", "class_p_g_e_1_1_resource_view.html", "class_p_g_e_1_1_resource_view" ],
      [ "\u202AString", "class_p_g_e_1_1_string.html", "class_p_g_e_1_1_string" ],
      [ "\u202AStructuredData", "class_p_g_e_1_1_structured_data.html", "class_p_g_e_1_1_structured_data" ],
      [ "\u202ASysEvents", "class_p_g_e_1_1_sys_events.html", "class_p_g_e_1_1_sys_events" ],
      [ "\u202ACircularArray", "class_p_g_e_1_1_circular_array.html", "class_p_g_e_1_1_circular_array" ],
      [ "\u202AMeta", "struct_p_g_e_1_1_meta.html", "struct_p_g_e_1_1_meta" ],
      [ "\u202ANegator", "struct_p_g_e_1_1_negator.html", "struct_p_g_e_1_1_negator" ],
      [ "\u202APolymorphicHeap", "class_p_g_e_1_1_polymorphic_heap.html", "class_p_g_e_1_1_polymorphic_heap" ],
      [ "\u202ARange", "class_p_g_e_1_1_range.html", "class_p_g_e_1_1_range" ],
      [ "\u202AReference", "class_p_g_e_1_1_reference.html", "class_p_g_e_1_1_reference" ],
      [ "\u202ATemplateString", "struct_p_g_e_1_1_template_string.html", "struct_p_g_e_1_1_template_string" ]
    ] ]
];