// THIS FILE WILL BE OVERWRITTEN BY AUTOGENERATED CODE
// DO NOT EDIT

#include <String/Char.h>

using namespace PGE;

std::unordered_map<wchar, wchar> Char::folding;
std::unordered_map<wchar, wchar> Char::up;
std::unordered_map<wchar, wchar> Char::down;
